export default {
  LOGIN: {
    CHANGE_VALUE: 'LOGIN_CHANGE_VALUE',
    AUTH: 'LOGIN_AUTH',
    LOGOUT: 'LOGOUT_AUTH',
  },

  REDIRECT: {
    OS: 'INICIAL_STATE_REDIRECT_OS',
    PRODUTO: 'INICIAL_STATE_REDIRECT_PRODUTO',
    FORNECEDOR: 'INICIAL_STATE_REDIRECT_FORNECEDOR',
    USUARIO: 'INICIAL_STATE_REDIRECT_USUARIO',
    TECNICO: 'INICIAL_STATE_REDIRECT_TECNICO',
    ENTRADA: 'INICIAL_STATE_REDIRECT_ENTRADA',
  }
}